---
- name: Ansible Test Playbook
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: ansible-bucka
    ansible_aws_ssm_region: eu-west-2
  tasks:
    # - name: Wait for connection
    #   ansible.builtin.wait_for_connection:

    - name: Copy file to EC2 instance
      ansible.builtin.copy:
        src: ../configs/plzwork.json
        dest: /app/config/plzwork.json
        owner: root
        group: root
        mode: '0644'
