---
- name: Ansible Test Playbook
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: ansible-bucka
    ansible_aws_ssm_region: us-west-2
  tasks:
    - name: Copy file to EC2 instance
      ansible.builtin.copy:
        src: ../configs/plzwork.json
        dest: /app/config/plzwork.json
        owner: root
        group: root
        mode: '0644'
