name: Runs an Ansible SSM Playbook
on:
  workflow_call:
    secrets: 
      GH_ASSUMABLE_AWS_ROLE:
        description: 'The ARN of the SSM GitHub Assumable AWS Role within SharedServices'
        required: true
      TARGET_ACCOUNT_AWS_ROLE:
        description: 'The ARN of the `config` role to be assumed in the target account'
        required: true

env: 
  AWS_REGION: ${{ vars.AWS_REGION }}
  BUCKET_NAME: ${{ vars.BUCKET_NAME }}

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        environment: ${{ fromJson(vars.ENVIRONMENTS) }}
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AWS Credentials - Assume SDLC Role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.GH_ASSUMABLE_AWS_ROLE }}
          aws-secret-access-key: ${{ secrets.TARGET_ACCOUNT_AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install additional dependencies for Ansible
        run: |
          source /opt/pipx/venvs/ansible-core/bin/activate
          python -m pip install boto3

      - name: Run Ansible playbook
        run: |
          ansible-playbook main.yml -i aws_ec2.yml --extra-vars "bucket_name=$BUCKET_NAME" -vvv
        working-directory: ./ansible