name: Ansible test
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  ansible-ssm:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AWS Credentials - Assume SharedServices GitHub Assumable Role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install additional dependencies for Ansible
        run: |
          source /opt/pipx/venvs/ansible-core/bin/activate
          python -m pip install boto3

      - name: Run Ansible playbook
        run: |
          ansible-playbook linux.yml -i aws_ec2.yml --extra-vars "bucket_name=$BUCKET_NAME" -vvv
        working-directory: ./ansible