name: Initialise Amplify application
run-name: App initialised by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      AMPLIFY_APP_NAME:
        type: string
        required: true
        description: The name of the new Amplify application!

jobs:
  create-amplify-app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Amplify
        uses: ./.github/actions/setup-amplify
        with:
          AWS_GHA_ROLE_ARN: ${{ vars.AWS_GHA_ROLE_ARN }}
          AWS_REGION: ${{ vars.AWS_REGION}}

      - name: Create Amplify app
        run: amplify init --amplify "{\"projectName\":\"${{ inputs.AMPLIFY_APP_NAME }}\"}" --yes | tee output.txt

      - name: Get Amplify App ID
        id: get_amplify_app_id
        run: |
          url=$(cat output.txt | grep -o "Adding backend environment dev to AWS Amplify app: [[:alnum:]]*" | awk '{print $NF}')
          echo "amplify_app_id=$url" >> $GITHUB_OUTPUT

      - name: Set Amplify App ID as GitHub repo variable
        run: gh variable set AMPLIFY_APP_ID --body ${{ steps.get_amplify_app_id.outputs.amplify_app_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create `prod` environment
        run: amplify env add --envName prod --yes

      - name: Commit Amplify files
        run: |
          git config --global user.name 'AmplifyEnvManager'
          git config --global user.email 'amplifysux@users.noreply.github.com'
          git add . && git commit -am 'feat: create amplify app `${{ inputs.AMPLIFY_APP_NAME }}`' && git push
          git fetch origin prod --depth 1 && git checkout prod
          git merge dev --no-edit && git push