name: Destroy Amplify environment (auto)
run-name: PR closed - deleting backend environment

on:
  delete:
  pull_request:
    types: [opened, reopened, closed]
  push:

jobs:
  destroy-amplify-env-auto:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        run: |
          echo "ref_name ${{ github.ref_name }}"
          echo "ref ${{ github.event.ref }}"
          echo "head_ref ${{ github.head_ref }}"
          echo "base_ref ${{ github.base_ref }}"
          echo "test ${{ github.event.pull_request.head.ref }}"