name: Destroy Amplify environment (auto)
run-name: PR closed - deleting backend environment

on:
  pull_request:
    types: [opened, reopened]

jobs:
  destroy-amplify-env-auto:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.head_ref }}

      - name: Test
        run: |
          echo "ref_name ${{ github.ref_name }}"
          echo "ref ${{ github.event.ref }}"
          echo "head_ref ${{ github.head_ref }}"
          echo "base_ref ${{ github.base_ref }}"
          echo "test ${{ github.event.pull_request.head.ref }}"

      - name: Hello
        run: touch "test.txt"

      # Amplify needs local files to be committed to know which environments it can pull (it sucks, I know)
      - name: Commit Amplify local environment
        run: |
          git config --global user.name 'AmplifyEnvManager'
          git config --global user.email 'amplifysux@users.noreply.github.com'
          git commit -am 'chore: new amplify environment `abcdef`'
          git push
        shell: bash
