name: Checkout Amplify environment

on:
  workflow_call:
  push:
    branches:
      - master
  
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: CACHE ACTION
        uses: actions/cache@v3
        id: amplify-cache
        with:
            path: |
                /usr/local/bin/amplify
                /usr/local/bin/expo-cli
            key: ${{ runner.os }}-amplify-${{ hashFiles('/usr/local/bin/amplify', '/usr/local/bin/expo-cli' ) }}
            restore-keys: |
                ${{ runner.os }}-amplify-
                ${{ runner.os }}-

      - name: Installing dependencies
        if: steps.amplify-cache.outputs.cache-hit != 'true'
        run: |
            echo "CACHE MISS"
            npm install -g expo-cli @aws-amplify/cli 

      - name: test
        run: |
            which amplify
            which expo
            cat /usr/local/bin/amplify
            cat /usr/local/bin/expo-cli