name: Runs the job loader script
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master

jobs:
  setup-env:
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(vars.ENVIRONMENTS) }}

    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    outputs:
      ENVIRONMENT: ${{ matrix.environment }}
      AUT_ENVIRONMENTS: ${{ vars.AUT_ENVIRONMENTS }}

    steps:
      - name: A useless but needed step
        run: echo "${{ vars.AUT_ENVIRONMENTS }}"

  job-loader:
    needs: setup-env
    runs-on: ubuntu-latest
    environment: ${{ needs.setup-env.outputs.ENVIRONMENT }}

    strategy:
      fail-fast: false
      matrix:
        aut_environment: ${{ fromJson(needs.setup-env.outputs.AUT_ENVIRONMENTS)}}

    steps:
      - name: Echo variables
        run: echo "${{ needs.setup-env.outputs.ENVIRONMENT }} - ${{ matrix.aut_environment }}"
