name: Run `pre-commit`

on:
  push:
    branches:
      - dev

jobs:
  check-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
