name: Ansible test
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  ansible-ssm:
    uses: endrizzimarco/pipeline-challenge/.github/workflows/ansible_ssm.yaml@master
    secrets: 
      GH_ASSUMABLE_AWS_ROLE: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TARGET_ACCOUNT_AWS_ROLE: ${{ secrets.AWS_SECRET_ACCESS_KEY }}